### ISSUE TITLE
Inserting spaces into input code

### ISSUE THREAD

**Issue by celine168** [LibreTexts/ckeditor-binder-plugin#10]
I noticed when I press 'space' inside the code input box, it doesn't show up/the cursor doesn't move until I press another character. I don't know if this is only an issue from my end.

**Comment by narrator0** [comment]
This issue somehow don't exist on production. I think it is because there exists a different set of CodeMirror theme on production that makes it different from development where it is the basic theme.

**Comment by narrator0** [comment]
Closing. Not an issue on production.
