### ISSUE TITLE
Tracking a more recent commit (or master branch) of Thebe instead of v0.5.1

### ISSUE THREAD

**Issue by celine168** [LibreTexts/ckeditor-binder-plugin#123]
[v0.5.1 of Thebe](https://github.com/executablebooks/thebe/releases) was released in Oct. 29, 2019, which is more than a year ago. Since then, there have been changes such as Kevin's PR for reusing binder sessions, a restart and run all button, and more. 

@rkevin-arch and I want to suggest tracking the master branch of Thebe or a more recent commit of Thebe for the plugin, which we could manually bump up as new commits are made.

**Comment by celine168** [comment]
Meeting notes (12/1): We agreed to update the Thebe version when we update the default-env version in the plugin.

**Comment by narrator0** [comment]
As we are currently loading from `https://unpkg.com/thebelab@0.5.1/lib/index.js` this path, we might need some other way to build a later version. Currently thebe only deploy to unpkg when a release is created so no later package on unpkg that we can use.

**Comment by moorepants** [comment]
This is related to the discussion here: https://github.com/executablebooks/thebe/issues/285

There needs to be a way to provide the js library from the tip of the master branch, as dev version of the library. If that was available, we could use it. So, this needs to be solved over at thebe first.

**Comment by celine168** [comment]
The errors they are running into seem to be related to building the documentation rather than Thebe itself (I might be reading into the issue wrong though). 
In development, Thebe seems to build fine?

**Comment by celine168** [comment]
Posted issue here: https://github.com/executablebooks/thebe/issues/322
Replied to PR here: https://github.com/executablebooks/thebe/pull/298 (I think something's wrong with my python installation so I am unable to run his PR)

**Comment by Miniland1333** [comment]
Will this issue be closed by #135 since it points to an updated thebe release?

**Comment by moorepants** [comment]
Yes, the solution is that we have to manually release thebe as needed.
