### ISSUE TITLE
Add option for making a cell Read-Only

### ISSUE THREAD

**Issue by Miniland1333** [LibreTexts/ckeditor-binder-plugin#138]
With the newest release of thebe, we now have the [option for cells to be read-only](https://thebe.readthedocs.io/en/latest/configure.html#mark-a-code-cell-as-read-only).

There are two simple modifications that need to be made to enable this functionality with our binder-plugin:
1. Add a checkbox or toggle button in the plugin to toggle readOnly mode for a cell.
2. Modify the dialog's output to add or remove the `data-readonly` attribute.

**Comment by sandertyu** [comment]
We have such an option on staging, and it works fine on libretexts.org. However, I can't seem to get it to work properly on our local development version.

**Comment by TimStewartJ** [comment]
I'm not sure why that might be happening for you, it should work fine locally.

**Comment by TimStewartJ** [comment]
Finished in 1.11.0 release (#170).
