### ISSUE TITLE
make sure ipywidgets works

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#22]
### Todos
- [ ] make matplotlib work on the thebelab editor
~~make matplotlib work when output embeded~~
- [x] make ipyleaflet work on the thebelab editor
~~make ipyleaflet work when output enbeded~~

### Edit (2/1 2020)

We decide not to support output caching for now.

**Comment by tannavee** [comment]
tested out ipywidgets, using the test commands on the site, and it seems to work

**Comment by tannavee** [comment]
![image](https://user-images.githubusercontent.com/53124295/73114449-76c51000-3ecf-11ea-9070-a96bc3dffca9.png)

**Comment by tannavee** [comment]
Currently with matplotlib widgets

![image](https://user-images.githubusercontent.com/53124295/73338484-8c1d9f80-422b-11ea-8958-418215d1ecd2.png)

**Comment by tannavee** [comment]
widgets work, but somehow the symbols don't show, and the way to know what widgets do what is by hovering mouse over box, and also area where arrow points also lets the user know.

@narrator0 @celine168 do you think this is a thebelab issue, or matplotlib widgets issue?

**Comment by narrator0** [comment]
We decide to not support for output cache for the widgets for now. But have to detect if the user are using a widget and then show a notification to the user.
