### ISSUE TITLE
Pressing source button removes tag attributes for thebelab

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#33]
### What happened?

Pressing the `source ` button of CKeditor and then switch back to Html edit mode will remove tag attributes like `executable="true"`.

### What is expected to happen?

Attributes should stay the same.

### Information that may be useful

* [Content filtering in CKeditor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html)

**Comment by celine168** [comment]
I've noticed this too unfortunately :/ but I was hoping it was only on the dev environment.

**Comment by celine168** [comment]
This doesn't seem to happen on production, but later we should later make it universal so that this doesn't happen to others.
