### ISSUE TITLE
Point plugin to our own binder

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#39]
LibreTexts books/pages to check:

- [x] https://chem.libretexts.org/Courses/Intercollegiate_Courses/Internet_of_Science_Things_(2020)/2%3A_Python_Modules/2.02%3A_Input_and_Variables_in_Python
- [x] https://eng.libretexts.org/Bookshelves/Industrial_and_Systems_Engineering/Book%3A_Introduction_to_Control_Systems_(Iqbal)/01%3A_Mathematical_Models_of_Physical_Systems/1.09%3A_Transfer_Function_Models
- [ ] https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Visual_Statistics_Use_R_(Shipunov)/03%3A_Types_of_Data/3.09%3A_Answers_to_exercises
- [ ] https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Visual_Statistics_Use_R_(Shipunov)/08%3A_Appendix_A-_Example_of_R_session/8.03%3A_A.3-_Plotting...
- add more here

**Comment by Miniland1333** [comment]
Reopened as of https://github.com/LibreTexts/ckeditor-binder-plugin/commit/16c96d45e435fc2f55caaf349fe8e769fd05bcdc

**Comment by narrator0** [comment]
Our current binder is somehow unable to support R even after upgrading to a newer version. Move to medium priority as we think is it ok to use mybinder for now.

**Comment by Miniland1333** [comment]
Do you have a reference/link to the issue that tracks support for R on your binder?

**Comment by celine168** [comment]
I think I discussed this before with you, but using a Dockerfile for R does work. 
https://github.com/LibreTexts/ckeditor-binder-plugin/tree/fix/use-libretexts-binder

**Comment by Miniland1333** [comment]
Hello @LibreTexts/jupyter-team! I wanted to poke this issue as it looks like the LibreTexts integration is still using mybinder over your instance. Since we've been using mybinder, we have received comments that it is too slow to load which is understandable.

https://github.com/LibreTexts/ckeditor-binder-plugin/blob/0718e15efab8cdf1d209d97461e420c43581af9b/src/scripts/activateThebelab.js#L3

If there aren't any residual issues, I would recommend changing this back and seeing if LibreText's users notice the difference.
-Henry

**Comment by Miniland1333** [comment]
I have increased the priority of this issue both because the slowness is hindering the usage of Jupyter on LibreTexts and because this issue has been sitting for quite a while.

**Comment by sandertyu** [comment]
Sorry for leaving it in this untouched state @Miniland1333 . We've been discussing switching CKEditor back to our binder.libretexts.org , and we should hopefully have this done even before the weekend is over.

**Comment by moorepants** [comment]
Before switching to production, I want confirmation that we will not break existing pages on LIbretexts pages that are already using the ckeditor plugin.

**Comment by Miniland1333** [comment]
Sounds like a plan to me! Please @me whenever this is deployed and I will pass it on to Dr. Larsen since he is the one who brought up the visible slowness today.

**Comment by sandertyu** [comment]
@Miniland1333 Like Jason said, we need to verify that each Libretext page which currently works using mybinder.org will also work on binder.libretexts.org (testing on query). We were thinking about searching through every page for the `<pre data-executable="true">` or `<div class="thebelab-widget">` html tag across all of the libretext pages to identify which ones use the CKEditor plugin. Do you know of any way to do this, or alternative method to check for pages which are using the plugin?

**Comment by Miniland1333** [comment]
We do have a tool that will be able to do a find on the site. I've sent you in an email the pages it found for eng.libretexts.org since I would guess it has the most people already using the plugin.

**Comment by moorepants** [comment]
Looks like the google search "restart site:libretexts.org" does a decent job finding pages. "restart" isn't used often in normal textbook text but is used on our button. Note that "thebelab-widget site:libretexts.org" doesn't return results on google. I guess it doesn't search the source code.

**Comment by moorepants** [comment]
I've put some pages I've found above to check in a list.

**Comment by sandertyu** [comment]
I think this specific issue can also be closed. There are still some issues with the change, but we have updated CKEditor to use our binder.libretexts.org as the issue asks.
