### ISSUE TITLE
Create an instruction page on how to use the widgets

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#54]
Need to create an instruction page on how to use the widgets for book authors. Potentially a Github page or maybe just a markdown file.

**Comment by sandertyu** [comment]
I've started making a few construction pages on LibreTexts. A full list of the widgets and their status on LibreTexts is available [here](https://github.com/sandertyu/widgetstuffs/blob/master/README.md).

In the following list, I've set links to the construction page where it has been created. The checkboxes are there for when the widget page is done being written or the only thing remaining is the widget does not fully work atm. Be sure to include the bugs/limitations on the construction guide.
- [x] [ipympl](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipywidgets_for_Interactivity/Enabling_and_Using_Interactive_Matplotlib_Features)
- [x] [ipyleaflet](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipywidgets_for_Interactivity/Enabling_and_Using_Interactive_Matplotlib_Features/Using_ipyleaflet_for_Interactive_Mapping)
- [x] [pythreejs](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.08%3A_Using_ipywidgets_for_Interactivity/5.2.8.01%3A_Enabling_and_Using_Interactive_Matplotlib_Features/5.2.8.1.4%3A_Using_pythreejs_to_generate_and_view_three-dimensional_models)
- [x] [ipywidgets](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipywidgets_for_Interactivity)
- [x] [bqplot](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.08%3A_Using_ipywidgets_for_Interactivity/5.2.8.01%3A_Enabling_and_Using_Interactive_Matplotlib_Features/5.2.8.1.5%3A_Using_bqplot_to_make_interactive_plots)
- [x] [ipyvolume](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.08%3A_Using_ipywidgets_for_Interactivity/5.2.8.01%3A_Enabling_and_Using_Interactive_Matplotlib_Features/5.2.8.1.02%3A_Using_ipyvolume_for_3D_plotting) (not installed)
- [x] [nglview](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.08%3A_Using_ipywidgets_for_Interactivity/5.2.8.01%3A_Enabling_and_Using_Interactive_Matplotlib_Features/5.2.8.1.03%3A_Using_nglview_to_view_molecular_structures_and_trajectories)
- [x] [ipycytoscape](https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.08%3A_Using_ipywidgets_for_Interactivity/5.2.8.7%3A_Using_IPyCytoscape_to_visualize_graphs)

**Comment by TimStewartJ** [comment]
Instruction (or at least example) pages exist for all of the above widgets now.
