### ISSUE TITLE
Make sure interactive buttons work on matplotlib widgets.

### ISSUE THREAD

**Issue by tannavee** [LibreTexts/ckeditor-binder-plugin#57]
The icons now appear when you add ```%matplotlib widget```. However, you can't use the interactive buttons

**Comment by sandertyu** [comment]
It seems that something behind the scenes has changed to allow `%matplotlib widget` buttons to work properly for most cases. However, the forward/previous/original view buttons do not work when a 3D plot is being displayed. They seem to consistently work when the plot is just 2D though.

Examples here: https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/Using_ipywidgets_for_Interactivity/Enabling_and_Using_Interactive_Matplotlib_Features

**Comment by moorepants** [comment]
This page now works.
