### ISSUE TITLE
define HTML structure

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/ckeditor-binder-plugin#60]
To ensure all we never have to go back and change the HTML structure for our plugin, we need to redefine our HTML structure. The current structure is as below:

```html
  <div class="thebelab">
    <pre data-executable="true" data-language="python3">
      print('hello world')
    </pre>
    <div data-output="true">
      hello world
    </div>
  </div>
```

The only tag defined by us is the most outer tag.

**Comment by narrator0** [comment]
One thing we might need to fix is that sometimes there is a `pre` tag within data output. Might need to investigate a big to make this consistent.

**Comment by celine168** [comment]
That's a good catch. I would prefer for Thebelab to search for specific classes that we define instead. I will need to research to see if this is possible.

**Comment by narrator0** [comment]
Yes it is possible. You can set a custom css selector pattern for thebelab. But why do we need that? `data-executable` seems unique enough to me.

**Comment by celine168** [comment]
I was thinking of adding another class inside the pre element to prevent a pre tag in a data output to run, but I realized that class could be replicated as well. I'm not proposing a good solution.

**Comment by narrator0** [comment]
This is a good point though. If the output is `<pre data-executable>...</pre>` then it might be executed. However, I wouldn't worry too much since the output will probably not be an HTML tag in most cases. If we really want to fix this, we can escape the HTML tags, but again, I don't think we should worry about this.

**Comment by narrator0** [comment]
Two things that I think we should fix for now are:

1. Change `.thebelab` into something more specific since I can imagine this class being used by thebelab somehow in the future.
2. Always wrap a `pre` tag within the output area. I tested that this is the default behavior of thebelab.

I think this can be a possible structure:

```html
<div class="thebelab-widget">
  <pre data-executable="true" data-language="python3">
    print('hello world')
  </pre>
  <div data-output="true">
    <pre>
      hello world
    </pre>
  </div>
</div>
```
