### ISSUE TITLE
Brackets in editor converts to HTML before executing

### ISSUE THREAD

**Issue by celine168** [LibreTexts/ckeditor-binder-plugin#83]
Our plugin seems to convert `<` to `&lt;` or `>` to `&rt`, which confuses the C++ kernel. It also seems to confuse anything within brackets `< >`, for example, `#include <iostream>`.
![image](https://user-images.githubusercontent.com/22624020/80935827-4a007e80-8d83-11ea-8cf0-da028db98e8b.png)

**Comment by celine168** [comment]
Here's how it looks on the development environment: 
![image](https://user-images.githubusercontent.com/22624020/80936074-6650eb00-8d84-11ea-8027-5dee172dabae.png)

**Comment by narrator0** [comment]
Fixed in #84.
