### ISSUE TITLE
This repository needs an open source license

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/ckeditor-binder-plugin#90]
You may have to license it the same as ckeditor, if not I've been choosing MIT for most things lately.

**Comment by celine168** [comment]
> CKEditor 4 is distributed under three copyleft Open Source license options: GPL, LGPL and MPL. 

I saw in a forum that we shouldn't have to distribute it in the same licenses that CKEditor does.

**Comment by moorepants** [comment]
I think as long as it doesn't import any CKEditor code then we could use a different license, but it may be best to use one of those three so we don't take a chance.
