### ISSUE TITLE
If output text is too wide the modal goes off the screen and you can't press the buttons to the far right

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/ckeditor-binder-plugin#91]
I just did this:
![image](https://user-images.githubusercontent.com/276007/81752015-77c18380-9465-11ea-914d-6d0d557429cb.png)

The modal has to be forced to stay the width of the browser window or it will become unusable.

**Comment by narrator0** [comment]
We fixed the same issue with height before. Didn't notice that the width also blows off. I can fix that.

**Comment by celine168** [comment]
Was taking a glance at this earlier and I didn't think that setting a max-width on `.mt-editor-dialog-binderDialog` worked.
