### ISSUE TITLE
Loading kernels on LIbreTexts can take a long time and there is no feedback to the user

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/ckeditor-binder-plugin#99]
If you go to a binderhub and fire up a new kernel there is a progress bar that shows everything going on. This is useful feedback to the user so they know things are working and will be more likely to patiently wait. In our LibreTexts plugin the use sits with the modal and no feedback after pressing run. Sometimes this takes a long time and you don't know if there might be errors. I've been waiting over a minute for the octave kernel to load and execute, for example.

**Comment by sandertyu** [comment]
Thebelab has status buttons that allow users to see the current state of the kernel. We would have to discuss how and where to implement them, but it's something we can try to do. An example is seen [here](https://thebelab.readthedocs.io/en/latest/_static/activate_button.html).

**Comment by moorepants** [comment]
A couple more notes:

- When someone is reading and interacting with the pages' cells both the run and restart buttons should indicate what is happening "restarting kernel...", "running computation...", "starting kernel...", etc.
- When a page author is editing their code in the popup modal, they should see the same kind of feedback.

**Comment by moorepants** [comment]
If you use binder directly it, optionally, provides a lot of feedback:
![Selection_725](https://user-images.githubusercontent.com/276007/89286944-5979b700-d653-11ea-9bfa-b481cc04ad58.png)

There is the horizontal progress bar and if you unhide the black window it shows the entire build log. This is very helpful to see what's going on if things don't work. Implementing either or both of these would improve this plugin.

**Comment by narrator0** [comment]
Resolved by #122
